# Use a imagem oficial do Node.js como base
FROM node:14

# Crie um diretório de trabalho no contêiner
WORKDIR /usr/src/app

# Copie o arquivo package.json e o arquivo package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instale as dependências do aplicativo
RUN npm install

# Copie o restante do código-fonte do aplicativo para o diretório de trabalho
COPY . .

# Expõe a porta em que o aplicativo irá escutar (ajuste de acordo com a porta do seu aplicativo)
EXPOSE 8080

# Comando para iniciar o aplicativo quando o contêiner for iniciado
CMD ["node", "app.js"]